### ISSUE TITLE
DUB target type to build a static library

### ISSUE THREAD

**Issue by ghost** [jaypha/fixed#2]
DUB does nothing with your library because the target type is _sourceLibrary_, wouldn't it make more sense to change it to _library_ ?

**Comment by jaypha** [comment]
I'll admit I am not an expert on DUB, but my understanding is that library causes a library binary to be created, whereas sourceLibrary does not, and the source files are compiled directly into your project.

My reasoning is that a single file does not justify the creation of a separate library. I may be wrong. I placed a post in the DUB forums, but have received no reply as yet. I will keep this issue open for the time being.

Regards
