### ISSUE TITLE
asString vs toString ?

### ISSUE THREAD

**Issue by ghost** [jaypha/fixed#3]
if you add `alias toString = asString` to the Fixed structure this would allow pretty printing and automating formating of the value (write, writeln, format, std.conv.to, etc.).

Any reason explaining why you don't use it ?

**Comment by jaypha** [comment]
I have added the method `pure string toString() const` to the definition.

I have had issues of conflicts in the past, and tended to shy away from sharing function names. However, if this is not the case now, then it makes sense to have it. If there are no problems with the new method, then `asString` will be deprecated.
